name: CI

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
    paths-ignore:
      - "**/README.md"
  schedule:
    - cron: "50 7 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.project }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          ["blinky", "button", "button-interrupt", "hello-world", "panic"]
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@v1
        with:
          target: riscv32imc-unknown-none-elf
          toolchain: nightly
          components: rust-src

      - run: cargo build --release
        working-directory: ${{ matrix.project }}

